package cc.buckler.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.port
     *
     * @mbg.generated
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.passwd
     *
     * @mbg.generated
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.transfer_enable
     *
     * @mbg.generated
     */
    private Long transferEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u
     *
     * @mbg.generated
     */
    private Long u;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.d
     *
     * @mbg.generated
     */
    private Long d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.t
     *
     * @mbg.generated
     */
    private Integer t;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.enable
     *
     * @mbg.generated
     */
    private Byte enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.method
     *
     * @mbg.generated
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.custom_method
     *
     * @mbg.generated
     */
    private String customMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.protocol
     *
     * @mbg.generated
     */
    private String protocol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.protocol_param
     *
     * @mbg.generated
     */
    private String protocolParam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.obfs
     *
     * @mbg.generated
     */
    private String obfs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.obfs_param
     *
     * @mbg.generated
     */
    private String obfsParam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.speed_limit_per_con
     *
     * @mbg.generated
     */
    private Integer speedLimitPerCon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.speed_limit_per_user
     *
     * @mbg.generated
     */
    private Integer speedLimitPerUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbg.generated
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wechat
     *
     * @mbg.generated
     */
    private String wechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qq
     *
     * @mbg.generated
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usage
     *
     * @mbg.generated
     */
    private Byte usage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pay_way
     *
     * @mbg.generated
     */
    private Byte payWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.balance
     *
     * @mbg.generated
     */
    private BigDecimal balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.enable_time
     *
     * @mbg.generated
     */
    private Date enableTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.expire_time
     *
     * @mbg.generated
     */
    private Date expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ban_time
     *
     * @mbg.generated
     */
    private Integer banTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.level
     *
     * @mbg.generated
     */
    private Byte level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_admin
     *
     * @mbg.generated
     */
    private Byte isAdmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.reg_ip
     *
     * @mbg.generated
     */
    private String regIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_login
     *
     * @mbg.generated
     */
    private Integer lastLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.referral_uid
     *
     * @mbg.generated
     */
    private Integer referralUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.port
     *
     * @return the value of user.port
     *
     * @mbg.generated
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.port
     *
     * @param port the value for user.port
     *
     * @mbg.generated
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.passwd
     *
     * @return the value of user.passwd
     *
     * @mbg.generated
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.passwd
     *
     * @param passwd the value for user.passwd
     *
     * @mbg.generated
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.transfer_enable
     *
     * @return the value of user.transfer_enable
     *
     * @mbg.generated
     */
    public Long getTransferEnable() {
        return transferEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.transfer_enable
     *
     * @param transferEnable the value for user.transfer_enable
     *
     * @mbg.generated
     */
    public void setTransferEnable(Long transferEnable) {
        this.transferEnable = transferEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u
     *
     * @return the value of user.u
     *
     * @mbg.generated
     */
    public Long getU() {
        return u;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u
     *
     * @param u the value for user.u
     *
     * @mbg.generated
     */
    public void setU(Long u) {
        this.u = u;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.d
     *
     * @return the value of user.d
     *
     * @mbg.generated
     */
    public Long getD() {
        return d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.d
     *
     * @param d the value for user.d
     *
     * @mbg.generated
     */
    public void setD(Long d) {
        this.d = d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.t
     *
     * @return the value of user.t
     *
     * @mbg.generated
     */
    public Integer getT() {
        return t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.t
     *
     * @param t the value for user.t
     *
     * @mbg.generated
     */
    public void setT(Integer t) {
        this.t = t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.enable
     *
     * @return the value of user.enable
     *
     * @mbg.generated
     */
    public Byte getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.enable
     *
     * @param enable the value for user.enable
     *
     * @mbg.generated
     */
    public void setEnable(Byte enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.method
     *
     * @return the value of user.method
     *
     * @mbg.generated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.method
     *
     * @param method the value for user.method
     *
     * @mbg.generated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.custom_method
     *
     * @return the value of user.custom_method
     *
     * @mbg.generated
     */
    public String getCustomMethod() {
        return customMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.custom_method
     *
     * @param customMethod the value for user.custom_method
     *
     * @mbg.generated
     */
    public void setCustomMethod(String customMethod) {
        this.customMethod = customMethod == null ? null : customMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.protocol
     *
     * @return the value of user.protocol
     *
     * @mbg.generated
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.protocol
     *
     * @param protocol the value for user.protocol
     *
     * @mbg.generated
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol == null ? null : protocol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.protocol_param
     *
     * @return the value of user.protocol_param
     *
     * @mbg.generated
     */
    public String getProtocolParam() {
        return protocolParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.protocol_param
     *
     * @param protocolParam the value for user.protocol_param
     *
     * @mbg.generated
     */
    public void setProtocolParam(String protocolParam) {
        this.protocolParam = protocolParam == null ? null : protocolParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.obfs
     *
     * @return the value of user.obfs
     *
     * @mbg.generated
     */
    public String getObfs() {
        return obfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.obfs
     *
     * @param obfs the value for user.obfs
     *
     * @mbg.generated
     */
    public void setObfs(String obfs) {
        this.obfs = obfs == null ? null : obfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.obfs_param
     *
     * @return the value of user.obfs_param
     *
     * @mbg.generated
     */
    public String getObfsParam() {
        return obfsParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.obfs_param
     *
     * @param obfsParam the value for user.obfs_param
     *
     * @mbg.generated
     */
    public void setObfsParam(String obfsParam) {
        this.obfsParam = obfsParam == null ? null : obfsParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.speed_limit_per_con
     *
     * @return the value of user.speed_limit_per_con
     *
     * @mbg.generated
     */
    public Integer getSpeedLimitPerCon() {
        return speedLimitPerCon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.speed_limit_per_con
     *
     * @param speedLimitPerCon the value for user.speed_limit_per_con
     *
     * @mbg.generated
     */
    public void setSpeedLimitPerCon(Integer speedLimitPerCon) {
        this.speedLimitPerCon = speedLimitPerCon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.speed_limit_per_user
     *
     * @return the value of user.speed_limit_per_user
     *
     * @mbg.generated
     */
    public Integer getSpeedLimitPerUser() {
        return speedLimitPerUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.speed_limit_per_user
     *
     * @param speedLimitPerUser the value for user.speed_limit_per_user
     *
     * @mbg.generated
     */
    public void setSpeedLimitPerUser(Integer speedLimitPerUser) {
        this.speedLimitPerUser = speedLimitPerUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gender
     *
     * @return the value of user.gender
     *
     * @mbg.generated
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gender
     *
     * @param gender the value for user.gender
     *
     * @mbg.generated
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wechat
     *
     * @return the value of user.wechat
     *
     * @mbg.generated
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wechat
     *
     * @param wechat the value for user.wechat
     *
     * @mbg.generated
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.qq
     *
     * @return the value of user.qq
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.qq
     *
     * @param qq the value for user.qq
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usage
     *
     * @return the value of user.usage
     *
     * @mbg.generated
     */
    public Byte getUsage() {
        return usage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usage
     *
     * @param usage the value for user.usage
     *
     * @mbg.generated
     */
    public void setUsage(Byte usage) {
        this.usage = usage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pay_way
     *
     * @return the value of user.pay_way
     *
     * @mbg.generated
     */
    public Byte getPayWay() {
        return payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pay_way
     *
     * @param payWay the value for user.pay_way
     *
     * @mbg.generated
     */
    public void setPayWay(Byte payWay) {
        this.payWay = payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.balance
     *
     * @return the value of user.balance
     *
     * @mbg.generated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.balance
     *
     * @param balance the value for user.balance
     *
     * @mbg.generated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.score
     *
     * @return the value of user.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.score
     *
     * @param score the value for user.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.enable_time
     *
     * @return the value of user.enable_time
     *
     * @mbg.generated
     */
    public Date getEnableTime() {
        return enableTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.enable_time
     *
     * @param enableTime the value for user.enable_time
     *
     * @mbg.generated
     */
    public void setEnableTime(Date enableTime) {
        this.enableTime = enableTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.expire_time
     *
     * @return the value of user.expire_time
     *
     * @mbg.generated
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.expire_time
     *
     * @param expireTime the value for user.expire_time
     *
     * @mbg.generated
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ban_time
     *
     * @return the value of user.ban_time
     *
     * @mbg.generated
     */
    public Integer getBanTime() {
        return banTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ban_time
     *
     * @param banTime the value for user.ban_time
     *
     * @mbg.generated
     */
    public void setBanTime(Integer banTime) {
        this.banTime = banTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.level
     *
     * @return the value of user.level
     *
     * @mbg.generated
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.level
     *
     * @param level the value for user.level
     *
     * @mbg.generated
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_admin
     *
     * @return the value of user.is_admin
     *
     * @mbg.generated
     */
    public Byte getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_admin
     *
     * @param isAdmin the value for user.is_admin
     *
     * @mbg.generated
     */
    public void setIsAdmin(Byte isAdmin) {
        this.isAdmin = isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.reg_ip
     *
     * @return the value of user.reg_ip
     *
     * @mbg.generated
     */
    public String getRegIp() {
        return regIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.reg_ip
     *
     * @param regIp the value for user.reg_ip
     *
     * @mbg.generated
     */
    public void setRegIp(String regIp) {
        this.regIp = regIp == null ? null : regIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_login
     *
     * @return the value of user.last_login
     *
     * @mbg.generated
     */
    public Integer getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_login
     *
     * @param lastLogin the value for user.last_login
     *
     * @mbg.generated
     */
    public void setLastLogin(Integer lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.referral_uid
     *
     * @return the value of user.referral_uid
     *
     * @mbg.generated
     */
    public Integer getReferralUid() {
        return referralUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.referral_uid
     *
     * @param referralUid the value for user.referral_uid
     *
     * @mbg.generated
     */
    public void setReferralUid(Integer referralUid) {
        this.referralUid = referralUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.status
     *
     * @return the value of user.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.status
     *
     * @param status the value for user.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.created_at
     *
     * @return the value of user.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.created_at
     *
     * @param createdAt the value for user.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.updated_at
     *
     * @return the value of user.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.updated_at
     *
     * @param updatedAt the value for user.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.remark
     *
     * @return the value of user.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.remark
     *
     * @param remark the value for user.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}